receivers:
  magic:

processors:
  batch:
    send_batch_size: 2

exporters:
  magic:
    name: exporter

service:
  pipelines:
    metrics:
      receivers: [magic]
      processors: [batch]
      exporters: [magic]