dist:
  name: otelcol-dev
  description: "Basic"
  output_path: ./otelcol-dev

receivers:
  - import: magicreceiver
    gomod: magicreceiver v0.64.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.68.0

replaces:
  - magicreceiver => ../