dist:
  name: otelcol-dev
  description: "Basic"
  output_path: ./otelcol-dev

receivers:
  - import: magicreceiver
    gomod: magicreceiver v0.64.0

exporters:
  - import: magicexporter
    gomod: magicexporter v0.64.0

replaces:
  - magicreceiver => ../
  - magicexporter => ../../../exporter/magicexporter