dist:
  name: otelcol-dev
  description: "Basic"
  output_path: ./otelcol-dev
  otelcol_version: 0.68.0

receivers:
  - import: magicreceiver
    gomod: magicreceiver v0.64.0

exporters:
  - import: magicexporter
    gomod: magicexporter v0.64.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.68.0

replaces:
  - magicreceiver => ../
  - magicexporter => ../../../exporter/magicexporter
